package com.thinkinginjava.error_handling_with_exceptions;

/**
 * <Thinking in Java 4th>
 *     -- chapter_12 通过异常处理错误
 *
 *  page 248
 *      示例与练习
 */